// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fslvosfclwtzfielelsh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZzbHZvc2ZjbHd0emZpZWxlbHNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzMjc4NjYsImV4cCI6MjA3MDkwMzg2Nn0.llNscA4Ra5IHg1at4pP1g485m1NXsAZ9od710nhbCKc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});